name: Release

on:
  release:
    types: released

permissions:
  contents: write

jobs:
  release-addon:
    runs-on: ubuntu-latest
    steps:
        - name: Set VERSION env
          run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
        - name: Checkout the source code
          uses: actions/checkout@v2
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release --no-archive
        - name: Move release to releases folder
          run:
            version="${{ github.event.release.tag_name }}"
            mv .hemttout/release "@STORM-Framework-${{ env.VERSION }}"
        - name: Zip release
          run: zip -r "@STORM-Framework-${{ env.VERSION }}.zip" ./@STORM-Framework-${{ env.VERSION }}
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: ./@STORM-Framework-${{ env.VERSION }}.zip
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Update to Steam Workshop (stable)
          uses: arma-actions/workshop-upload@v1
          with:
            itemId: '3224327412'
            contentPath: './@STORM-Framework-${{ env.VERSION }}'
            changelog: |
              https://github.com/OverlordZorn/S.T.O.R.M.-Framework/releases/tag/v${{ env.VERSION }}

              ${{ github.event.release.body }}
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
